### ISSUE TITLE
Merge an array and an object

### ISSUE THREAD

**Issue by alexander-rodin** [bomdia/vue-merge#3]
hello, when you try to merge an array and an object, all the fields from the object fall into the array

it was expected that in the field where the array was, there would be an object

https://codesandbox.io/s/determined-ritchie-jib7z
![image](https://user-images.githubusercontent.com/21691083/113559006-1759a880-961a-11eb-9c67-504060631f14.png)

**Comment by bomdia** [comment]
So if i understand well you want it to replace the existing array more than overwriting it, correct @alexander-rodin ?

**Comment by alexander-rodin** [comment]
I expected this behavior

![image](https://user-images.githubusercontent.com/21691083/113567523-35c6a080-9628-11eb-9e9e-91f9411a4141.png)

**Comment by bomdia** [comment]
I'll add a replaceArray option to behave like you want

**Comment by alexander-rodin** [comment]
thank you, that would be cool

**Comment by bomdia** [comment]
@alexander-rodin i've added the feauture try it and tell me if something goes wrong

**Comment by alexander-rodin** [comment]
> @alexander-rodin i've added the feauture try it and tell me if something goes wrong

is fine, thank you for your prompt help)

**Comment by bomdia** [comment]
No problem, feel free to open new issue if something goes wrong
